name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Add this line to enable manual triggers
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g electron-builder@latest

      - name: Build app
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            npm run build:mac
          else
            npm run build:win
          fi

      - name: Upload Mac Artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: mac-dmg
          path: dist/*.dmg
          if-no-files-found: error

      - name: Upload Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: win-exe
          path: dist/*.exe
          if-no-files-found: error